apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sample-site-cu-subscription
  namespace: sample-site-cu-subscription
  labels:
    app: sample-site-cu-subscription
  annotations:
    apps.open-cluster-management.io/git-path: manifests/sites/sample_site_cu
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: sample-site-cu-subscription/sample-site-cu-subscription 
  placement:
    local: true
